export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST"
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS"
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL"

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST"
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS"
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL"

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST"
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS"
export const MOVIE_DELETE_FAIL = "MOVIE_DELETE_FAIL"

export const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST"
export const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS"
export const MOVIE_CREATE_FAIL = "MOVIE_CREATE_FAIL"
export const MOVIE_CREATE_RESET = "MOVIE_CREATE_RESET"

export const MOVIE_UPDATE_REQUEST = "MOVIE_UPDATE_REQUEST"
export const MOVIE_UPDATE_SUCCESS = "MOVIE_UPDATE_SUCCESS"
export const MOVIE_UPDATE_FAIL = "MOVIE_UPDATE_FAIL"
export const MOVIE_UPDATE_RESET = "MOVIE_UPDATE_RESET"

export const MOVIE_CREATE_REVIEW_REQUEST = "MOVIE_CREATE_REVIEW_REQUEST"
export const MOVIE_CREATE_REVIEW_SUCCESS = "MOVIE_CREATE_REVIEW_SUCCESS"
export const MOVIE_CREATE_REVIEW_FAIL = "MOVIE_CREATE_REVIEW_FAIL"
export const MOVIE_CREATE_REVIEW_RESET = "MOVIE_CREATE_REVIEW_RESET"

export const MOVIE_TOP_REQUEST = "MOVIE_TOP_REQUEST"
export const MOVIE_TOP_SUCCESS = "MOVIE_TOP_SUCCESS"
export const MOVIE_TOP_FAIL = "MOVIE_TOP_FAIL"
