const Genres = {
  ACTION: 'Action',
  COMEDY: 'Comedy',
  DRAMA: 'Drama',
  HORROR: 'Horror',
  ROMANCE: 'Romance',
  SCIFI: 'Science Fiction',
  FANTASY: 'Fantasy',
  ANIMATION: 'Animation',
  DOCUMENTARY: 'Documentary',
  THRILLER: 'Thriller',
  MYSTERY: 'Mystery',
  CRIME: 'Crime',
  ADVENTURE: 'Adventure',
  HISTORICAL: 'Historical',
  WESTERN: 'Western',
  FAMILY: 'Family',
  MUSIC: 'Music',
  SPORTS: 'Sports',
  WAR: 'War',
  SUPERHERO: 'Superhero',
  SUSPENSE: 'Suspense',
  FANATSY: 'Fantasy',
  COMIC: 'Comic',
  REALITY: 'Reality',
  ROMANTIC_COMEDY: 'Romantic Comedy',
  SUPERNATURAL: 'Supernatural',
};

export default Genres;
